name: Build

on: [push]

jobs:
  build:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install required dependencies
        run: |
          . install.sh
                  
      - name: Run coverage and upload to codecov
        run: |
          LuaDist/bin/lua -lluacov main.test.lua
          LuaDist/bin/luacov
          bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
