name: Build

on: [push]

jobs:
  install:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install required dependencies
        run: |
          . install.sh
        
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Run coverage and upload to codecov
        run: |
          lua -lluacov main.test.lua
          bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
          
    
