name: Build

on: [push]

jobs:
  build:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install required dependencies
        run: |
          . install.sh
                  
      - name: Run coverage and upload to codecov
        run: |
          cd LuaDist/bin
          git submodule add -f https://github.com/Phrogz/Lunity.git
          cd; cd;  
          LuaDist/bin/lua -lluacov test.lua
          LuaDist/luacov
          bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
